name: 'Republish LDES'
description: 'Replicates a Linked Data Event Stream or tree:Collection to your GitHub repository'
inputs:
  url:
    description: 'URL to LDES or tree:Collection dataset'
    required: true
  storage:
    description: 'Output directory name where the fetched data will be stored'
    required: true
  gh_pages_url:
    description: 'URL to the GitHub Pages repository'
    required: false
    default: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'
  git_username:
    description: 'Git username that makes the commits'
    required: false
    default: 'LDES-action'
  git_email:
    description: 'Git email that makes the commits'
    required: false
    default: 'LDES-action@users.noreply.github.com'
  fragmentation_strategy:
    description: 'Fragmentation strategy to use'
    required: false
    default: 'version'
  fragmentation_page_size:
    description: 'RDF object count per page'
    required: false
    default: "50"
  datasource_strategy:
    description: 'Datasource strategy to use'
    required: false
    default: 'ldes-client'
  materialize_version:
    description: 'Wether version materialization should be used'
    required: false
    default: 'false'
outputs:
  delta_bytes: # size of changed data
    description: 'The overall number of bytes changed in the output data this run (current size - previous size)'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Run main script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_STORAGE: ${{ inputs.storage }}
        INPUT_GH_PAGES_URL: ${{ inputs.gh_pages_url }}
        INPUT_GIT_USERNAME: ${{ inputs.git_username }}
        INPUT_GIT_EMAIL: ${{ inputs.git_email }}
        INPUT_FRAGMENTATION_STRATEGY: ${{ inputs.fragmentation_strategy }}
        INPUT_FRAGMENTATION_PAGE_SIZE: ${{ inputs.fragmentation_page_size }}
        INPUT_DATASOURCE_STRATEGY: ${{ inputs.datasource_strategy }}
        INPUT_MATERIALIZE_VERSION: ${{ inputs.materialize_version }}
    - name: Run post script
      run: node ${{ github.action_path }}/dist/post/index.js
      shell: bash