name: 'Republish LDES'
description: 'Replicates a Linked Data Event Stream or tree:Collection to your GitHub repository'
inputs:
  url:
    description: 'URL to LDES or tree:Collection dataset'
    required: true
  storage:
    description: 'Output directory name where the fetched data will be stored'
    required: true
  postprocess:
    description: 'Javascript postprocessing file (should be in the root of the project)'
    required: false
  gh_pages_url:
    description: 'URL to the GitHub Pages repository'
    required: false
    default: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'
  git_username:
    description: 'Git username that makes the commits'
    required: false
    default: 'LDES-action'
  git_email:
    description: 'Git email that makes the commits'
    required: false
    default: 'LDES-action@users.noreply.github.com'
outputs:
  delta_bytes: # size of changed data
    description: 'The overall number of bytes changed in the output data this run (current size - previous size)'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Run main script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_STORAGE: ${{ inputs.storage }}
        INPUT_POSTPROCESS: ${{ inputs.postprocess }}
        INPUT_GH_PAGRS_URL: ${{ inputs.gh_pages_url }}
        INPUT_GIT_USERNAME: ${{ inputs.git_username }}
        INPUT_GIT_EMAIL: ${{ inputs.git_email }}
    - name: Run post script
      run: node ${{ github.action_path }}/dist/post/index.js
      shell: bash