name: 'Republish LDES'
description: 'Replicates a Linked Data Event Stream or tree:Collection to your GitHub repository'
inputs:
  url:
    description: 'URL to LDES or tree:Collection dataset'
    required: true
  storage:
    description: 'Output directory name where the fetched data will be stored'
    required: true
  postprocess:
    description: 'Javascript postprocessing file'
    required: false
outputs:
  delta_bytes: # size of changed data
    description: 'The overall number of bytes changed in the output data this run (current size - previous size)'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/post/index.js'